mysite2/mysite2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [

	url(r'^restaurantes/', include('restaurantes.urls')),
    url(r'^admin/', admin.site.urls),
    
]

mysite2/restaurantes/urls.py
from django.conf.urls import url


from . import views


app_name = 'restaurantes'
urlpatterns = [

	url(r'^registrar/$', views.RegistrarRestaurante.as_view(), name='registrar_restaurante'),
	url(r'^reportar/$', views.ReportarRestaurante.as_view(), name='reportar_restaurante'),
	url(r'^actualizar/(?P<pk>\d+)/$', views.ActualizarRestaurante.as_view(), name='actualizar_restaurante'),
	url(r'^reportar/$', views.EliminarRestaurante.as_view(), name='eliminar_restaurante'),
		
]

mysite2/restaurantes/models.py
from django.db import models

class Restaurate(models.Model):
	nombre = models.CharField(max_length=100)
	ubicacion = models.CharField(max_length=100)
	telefono = models.CharField(max_length=8)

	STATUS_ACTIVE = 1
	STATUS_DELETED = 2

	STATUS_CHOICES = (
			(STATUS_ACTIVE,'activo'),
			(STATUS_DELETED,'eliminado'),
		)
	status = models.SmallIntegerField(
			choices = STATUS_CHOICES,
			default = STATUS_ACTIVE,
		)
	def __str__(self):
		return self.nombre

class Menu(models.Model):
	restaurate = models.ForeignKey(Restaurate)
	plato = models.CharField(max_length=100)
	def __str__(self):
		return self.plato

mysite2/restaurantes/views.py
from django.views import generic
from django.shortcuts import get_object_or_404, render
from .models import Restaurate, Menu
from django.core.urlresolvers import reverse_lazy, reverse


class RegistrarRestaurante(generic.CreateView):
	template_name = 'restaurantes/registrar.html'
	fields="__all__"
	model = Restaurate
	success_url = reverse_lazy('restaurantes:reportar_restaurante')

class RestauranteView(generic.RedirectView):
	def get_redirect_url(self,*args, **kwargs):
		restaurante_obj = Restaurate.objects.get(id=kwargs.get('pk'))
		restaurante_obj.status = Restaurate.STATUS_DELETED
		restaurante_obj.save()
		return reverse('restaurantes:registrar_restaurante')

class ReportarRestaurante(generic.ListView):
	template_name = 'restaurantes/reportar.html'
	model = Restaurate
	def get_queryset(self):
		return Restaurate.objects.filter(status = Restaurate.STATUS_ACTIVE)

class ActualizarRestaurante(generic.UpdateView):
	template_name = 'restaurantes/actualizar.html'
	fields="__all__"
	model = Restaurate
	success_url = reverse_lazy('restaurantes:reportar_restaurante')
	template_name_suffix = '_update_form'
	
	

class EliminarRestaurante(generic.DeleteView):
	model = Restaurate
	success_url = reverse_lazy('restaurantes:reportar_restaurante')

mysite2/restaurantes/templates/restaurantes/actualizar.html
<!doctype html>
<html lag="en">
<head>
	<meta charset="UTF-8">
	<title>actualizar Restaurante</title>
</head>
<body>
	<h1>actualizar Restaurante</h1>
	<form action = "{% url 'restaurantes:actualizar_restaurante' restaurate.id %}"method="post">
	{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update" />
</form>
</body>
</html>

mysite2/restaurantes/templates/restaurantes/registrar.html
<!doctype html>
<html lag="en">
<head>
	<meta charset="UTF-8">
	<title>Registrar Restaurante</title>
</head>
<body>
	<h1>Registrar Restaurante</h1>
	<form method = "POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Registrar">
	</form>
</body>
</html>

mysite2/restaurantes/templates/restaurantes/reportar.html
<!doctype html>
<html lag="en">
<head>
	<meta charset="UTF-8">
	<title>Lista Restaurantes</title>
</head>
<body>

	<h1>Lista Restaurantes</h1>
	<form>
	<ul>
		<table border = "9" >	
		{% for restaurate in object_list %}
			<tr>
			<td><b>Nombre :</b>{{restaurate.nombre}}    </td>
			<td><b>Ubicacion :</b>{{restaurate.ubicacion}}    </td>
			<td><b>Telefono :</b>{{restaurate.telefono}}    </td>
			<td>
			<form action = "{% url 'restaurantes:eliminar_restaurante'%} {{restaurante.id}}" method = "POST">
				{% csrf_token %}	
    		<input type="submit" value="delete" />
			</form>
			</td>
			
			<td>
			
			<a href="{% url 'restaurantes:actualizar_restaurante' restaurate.id %}">actualizar</a>


			
			</td>
			</tr>
		{% endfor %}
		</table>
			
			<a href="{% url 'restaurantes:registrar_restaurante'%} {{restaurante.id}}">agregar</a>

			
	</ul>
	</form>	
</body>
</html>